version: "3.7"
services:
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

  app:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmina
    restart: always
    ports:
      - "80:80"
    environment:
      PMA_HOST: database